[tox]
envlist =
  py311
  py312
  # py313

[testenv]
# deps =
#   pipenv==2025.0.4

commands =
  # pipenv sync -d
  flake8
  black --check --diff monkeytype
  isort --check --diff monkeytype
  mypy monkeytype
  pytest

allowlist_externals =
  flake8
  black
  isort
  mypy
  pytest
